class RealUltrasonic:
    """
        Emulates a real ultrasonic sensor using the array of distance sensors
        generated by TotalUltrasonicSensor.proto.
        Note: Like a real ultrasonic sensor, getValue() returns a time period.
    """

    def __init__(self, robot, prefix, ray_count):
        self.rays = []
        for ray_id in range(ray_count):
            self.rays.append(robot.getDevice(f"{prefix}_ray({ray_id})"))

    def enable(self, sampling_rate):
        for ray in self.rays:
            ray.enable(sampling_rate)

    def getValue(self):
        return min(map(
            lambda ray: ray.getValue(),
            self.rays
        ))
